# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d47e9cdf0915df8dacf109b3c66d06b541d49c59dbebbadc1228982528ddcebaabe0e04decd591dd92b9bf610a08826ff8b1b9874f3cfdf87b06228e271279dc

test:
  secret_key_base: 839e035157aaaa2b7390207fe3f1766fe0c04ae0806a42ccc87fa135b5ef66dd363e95fae9ae11d135a87d0d1774f74867461d76c100a1360d04f0c61d698d7b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
